import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { t, DEFAULT_LOCALE, LOCALES, type Locale } from '@/lib/i18n';
import en from '@/locales/en.json';
import fr from '@/locales/fr.json';
import pt from '@/locales/pt.json';
import ar from '@/locales/ar.json';

const dictionary = en as Record<string, string>;

/**
 * Every source file the content rules can be violated in.
 *
 * The rules used to be checked against `en.json` alone, which is the one file
 * where they will never be broken: a fabricated metric arrives in a `.tsx` stat
 * card, "the Hub" and a per-resource "Verified" badge arrive in JSX, and a
 * hardcoded figure can arrive in a `.css` content property. Scanning the whole
 * of `src/` is what makes these guards mean anything.
 */
function sourceFiles(dir = 'src', out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) sourceFiles(full, out);
    else if (/\.(ts|tsx|css|json)$/.test(entry)) out.push(full);
  }
  return out;
}

/** Concatenated with a path marker before each file so a failure locates itself. */
const SOURCE = sourceFiles()
  .map((file) => `\n/* ${file} */\n${readFileSync(file, 'utf8')}`)
  .join('');

/**
 * The single global curation sentence (rule 10.8). It no longer carries the
 * word "verified" — dropped from the copy on 2026-09-09 — so that word is
 * not permitted anywhere in `src/` at all; see the test below.
 */
const CURATION_STATEMENT = 'Every resource is curated by the AI Hub team.';

/**
 * Generated by `npm run db:types` from the live schema, so a column name is not
 * a content decision. Non-empty guard: splitting on '' would shred the corpus.
 */
const GENERATED_TYPES =
  readFileSync('src/lib/supabase/database.types.ts', 'utf8') || '\0never\0';

describe('t()', () => {
  it('resolves a known key', () => {
    expect(t('site.name')).toBe('AI Hub for Sustainable Development');
  });

  it('returns the key itself for a missing lookup so gaps are visible', () => {
    // A blank string would hide the gap; the key renders as an obvious token.
    expect(t('does.not.exist')).toBe('does.not.exist');
  });

  it('interpolates named variables', () => {
    expect(t('deadline.daysLeft', { count: 6 })).toBe('6 days left');
  });

  it('leaves an unsupplied placeholder visibly intact', () => {
    expect(t('deadline.daysLeft')).toBe('{count} days left');
  });

  it('falls back to English per key, not per file, for an empty stub locale', () => {
    // This is the fallback that matters: PRD 12.4 ships fr/pt/ar empty and
    // fills them a string at a time, so every unfilled key must resolve to
    // English while the filled ones do not.
    expect(t('site.name', undefined, 'fr')).toBe(dictionary['site.name']);
  });

  it('still falls back at runtime for a locale that escaped the type', () => {
    // `locale` is typed `Locale`, so `'xx'` is a compile error — the cast is
    // deliberate and is what this test is about. A locale that arrives from a
    // URL segment or a cookie is a runtime string, and a narrowing bug at that
    // boundary must degrade to English rather than throw on the undefined
    // dictionary. The type is the primary guard; this is the backstop.
    expect(t('site.name', undefined, 'xx' as Locale)).toBe(dictionary['site.name']);
  });

  it('defaults to English', () => {
    expect(DEFAULT_LOCALE).toBe('en');
    // LOCALES is the single source of truth for what a Locale may be, and the
    // default must be a member of it.
    expect(LOCALES).toContain(DEFAULT_LOCALE);
  });
});

describe('en.json hygiene', () => {
  it('is flat — no nested objects', () => {
    for (const [key, value] of Object.entries(dictionary)) {
      expect(typeof value, `${key} is not a string`).toBe('string');
    }
  });

  it('has no empty values', () => {
    for (const [key, value] of Object.entries(dictionary)) {
      expect(value, `empty value for ${key}`).not.toBe('');
    }
  });

  it('ships fr, pt and ar stubs', () => {
    // PRD 12.4: adding a locale file makes that locale selectable with no
    // code change. The switcher itself is SP6.
    for (const stub of [fr, pt, ar]) {
      expect(typeof stub).toBe('object');
    }
  });
});

describe('PRD 10 exact wording, on the en.json keys that carry it', () => {
  it('uses the co-led attribution', () => {
    expect(dictionary['site.attribution']).toBe('co-led by MIMIT and UNDP');
  });

  it('carries the exact footer wording from rule 10.1', () => {
    expect(dictionary['site.footer']).toBe(
      'Co-led by the Ministry of Enterprises and Made in Italy and the United Nations Development Programme.',
    );
  });

  it('names the one mailbox', () => {
    expect(dictionary['site.contactEmail']).toBe('aihubfordevelopment@undp.org');
  });

  it('states curation once, globally', () => {
    // Rule 10.8 and PRD 16.1: stated once here, never per resource.
    expect(dictionary['site.curationStatement']).toBe(
      'Every resource is curated by the AI Hub team.',
    );
  });
});

/**
 * The prohibitions, run over `en.json` and every `.ts`/`.tsx`/`.css`/`.json`
 * file under `src/`. Case-insensitive throughout: a lowercase slip is the same
 * defect as a capitalised one.
 */
describe.each([
  ['en.json', JSON.stringify(en)],
  ['src/', SOURCE],
])('PRD 10 content rules — %s', (_label, all) => {
  it('never says "powered by" or "implemented by"', () => {
    // Rule 10.1: attribution is co-led, never delivery language.
    expect(all).not.toMatch(/powered by|implemented by/i);
  });

  it('never says "the Hub" alone', () => {
    // Rule 10.2: always "AI Hub" or "AI Hub for Sustainable Development".
    expect(all).not.toMatch(/\bthe hub\b(?! for)/i);
  });

  it('uses no mailbox other than aihubfordevelopment@undp.org', () => {
    // Rule 10.4. Every address found anywhere must be the single mailbox,
    // which catches a new one nobody thought to blocklist.
    const addresses = all.match(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g) ?? [];
    for (const address of addresses) {
      expect(address.toLowerCase(), `unexpected mailbox ${address}`).toBe(
        'aihubfordevelopment@undp.org',
      );
    }
  });

  it('has no per-resource Verified badge', () => {
    // Rule 10.8: curation is stated once, globally. The global curation
    // sentence is the ONLY place the word may appear, so it is removed from
    // the corpus by exact text and then nothing may be left. Exact rather than
    // a heuristic about badge-shaped labels: `'verified'`, `<span>Verified` and
    // a `resource.verified` key are all the same defect, and none of them is
    // reliably quoted or capitalised.
    //
    // The generated database.types.ts is excluded because a legitimate schema
    // column may carry the word; it holds no user-facing text.
    const withoutCuration = all
      .split(CURATION_STATEMENT)
      .join('')
      .split(GENERATED_TYPES)
      .join('');
    const hits = withoutCuration.match(/\bverified\b/gi) ?? [];
    expect(hits, `\`verified\` outside the global curation statement`).toEqual([]);
  });

  it('offers no "Global programmes" country filter value', () => {
    // Rule 10.6.
    expect(all).not.toMatch(/global\s+programmes/i);
  });

  it('spells Democratic Republic of the Congo in full', () => {
    // Rule 10.5: never "DR Congo" or "DRC".
    expect(all).not.toMatch(/\bDR\s+Congo\b/i);
    expect(all).not.toMatch(/\bDRC\b/);
  });

  it('carries no fabricated metric from the prototype GADATA block', () => {
    // PRD 8.4 and CLAUDE.md: a plausible fake number reaching production is a
    // launch-blocking defect. These are the prototype's invented figures, and
    // this must fail the moment one is pasted into a stat card.
    for (const figure of ['14,698', '12,840', '17,650', '2,583']) {
      expect(all, `fabricated figure ${figure}`).not.toContain(figure);
    }
  });
});
